.TH "AutoUTFOutputStream< CharType, OutputByteStream >" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AutoUTFOutputStream< CharType, OutputByteStream > \- Output stream wrapper with dynamically bound encoding and automatic encoding detection\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <encodedstream\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef CharType \fBCh\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAutoUTFOutputStream\fP (OutputByteStream &os, UTFType type, bool putBOM)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "UTFType \fBGetType\fP () const"
.br
.ti -1c
.RI "void \fBPut\fP (Ch c)"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.ti -1c
.RI "Ch \fBPeek\fP () const"
.br
.ti -1c
.RI "Ch \fBTake\fP ()"
.br
.ti -1c
.RI "size_t \fBTell\fP () const"
.br
.ti -1c
.RI "Ch * \fBPutBegin\fP ()"
.br
.ti -1c
.RI "size_t \fBPutEnd\fP (Ch *)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename CharType, typename OutputByteStream>
.br
class AutoUTFOutputStream< CharType, OutputByteStream >"
Output stream wrapper with dynamically bound encoding and automatic encoding detection\&. 


.PP
\fBTemplate Parameters:\fP
.RS 4
\fICharType\fP Type of character for writing\&. 
.br
\fIOutputByteStream\fP type of output byte stream to be wrapped\&. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<typename CharType , typename OutputByteStream > \fBAutoUTFOutputStream\fP< CharType, OutputByteStream >::\fBAutoUTFOutputStream\fP (OutputByteStream & os, UTFType type, bool putBOM)\fC [inline]\fP"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIos\fP output stream to be wrapped\&. 
.br
\fItype\fP UTF encoding type\&. 
.br
\fIputBOM\fP Whether to write BOM at the beginning of the stream\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
