.TH "AutoUTF< CharType >" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AutoUTF< CharType > \- Dynamically select encoding according to stream's runtime-specified UTF encoding type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <encodings\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBsupportUnicode\fP = 1 }"
.br
.ti -1c
.RI "typedef CharType \fBCh\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename OutputStream > static RAPIDJSON_FORCEINLINE void \fBEncode\fP (OutputStream &os, unsigned codepoint)"
.br
.ti -1c
.RI "template<typename OutputStream > static RAPIDJSON_FORCEINLINE void \fBEncodeUnsafe\fP (OutputStream &os, unsigned codepoint)"
.br
.ti -1c
.RI "template<typename InputStream > static RAPIDJSON_FORCEINLINE bool \fBDecode\fP (InputStream &is, unsigned *codepoint)"
.br
.ti -1c
.RI "template<typename InputStream , typename OutputStream > static RAPIDJSON_FORCEINLINE bool \fBValidate\fP (InputStream &is, OutputStream &os)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename CharType>
.br
struct AutoUTF< CharType >"
Dynamically select encoding according to stream's runtime-specified UTF encoding type\&. 


.PP
\fBNote:\fP
.RS 4
This class can be used with AutoUTFInputtStream and \fBAutoUTFOutputStream\fP, which provides GetType()\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
