.TH "BaseReaderHandler< Encoding, Derived >" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BaseReaderHandler< Encoding, Derived > \- Default implementation of Handler\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <reader\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Encoding::Ch \fBCh\fP"
.br
.ti -1c
.RI "typedef internal::SelectIf< internal::IsSame< Derived, void >, \fBBaseReaderHandler\fP, Derived >::\fBType\fP \fBOverride\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBDefault\fP ()"
.br
.ti -1c
.RI "bool \fBNull\fP ()"
.br
.ti -1c
.RI "bool \fBBool\fP (bool)"
.br
.ti -1c
.RI "bool \fBInt\fP (int)"
.br
.ti -1c
.RI "bool \fBUint\fP (unsigned)"
.br
.ti -1c
.RI "bool \fBInt64\fP (int64_t)"
.br
.ti -1c
.RI "bool \fBUint64\fP (uint64_t)"
.br
.ti -1c
.RI "bool \fBDouble\fP (double)"
.br
.ti -1c
.RI "bool \fBRawNumber\fP (const Ch *str, \fBSizeType\fP len, bool copy)"
.br
.RI "enabled via kParseNumbersAsStringsFlag, string is not null-terminated (use length) "
.ti -1c
.RI "bool \fBString\fP (const Ch *, \fBSizeType\fP, bool)"
.br
.ti -1c
.RI "bool \fBStartObject\fP ()"
.br
.ti -1c
.RI "bool \fBKey\fP (const Ch *str, \fBSizeType\fP len, bool copy)"
.br
.ti -1c
.RI "bool \fBEndObject\fP (\fBSizeType\fP)"
.br
.ti -1c
.RI "bool \fBStartArray\fP ()"
.br
.ti -1c
.RI "bool \fBEndArray\fP (\fBSizeType\fP)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Encoding = UTF8<>, typename Derived = void>
.br
struct BaseReaderHandler< Encoding, Derived >"
Default implementation of Handler\&. 

This can be used as base class of any reader handler\&. 
.PP
\fBNote:\fP
.RS 4
implements Handler concept 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
