.TH "BasicIStreamWrapper< StreamType >" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
BasicIStreamWrapper< StreamType > \- Wrapper of \fCstd::basic_istream\fP into RapidJSON's Stream concept\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <istreamwrapper\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef StreamType::char_type \fBCh\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBasicIStreamWrapper\fP (StreamType &stream)"
.br
.ti -1c
.RI "Ch \fBPeek\fP () const"
.br
.ti -1c
.RI "Ch \fBTake\fP ()"
.br
.ti -1c
.RI "size_t \fBTell\fP () const"
.br
.ti -1c
.RI "Ch * \fBPutBegin\fP ()"
.br
.ti -1c
.RI "void \fBPut\fP (Ch)"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.ti -1c
.RI "size_t \fBPutEnd\fP (Ch *)"
.br
.ti -1c
.RI "const Ch * \fBPeek4\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename StreamType>
.br
class BasicIStreamWrapper< StreamType >"
Wrapper of \fCstd::basic_istream\fP into RapidJSON's Stream concept\&. 

The classes can be wrapped including but not limited to:
.PP
.IP "\(bu" 2
\fCstd::istringstream\fP 
.IP "\(bu" 2
\fCstd::stringstream\fP 
.IP "\(bu" 2
\fCstd::wistringstream\fP 
.IP "\(bu" 2
\fCstd::wstringstream\fP 
.IP "\(bu" 2
\fCstd::ifstream\fP 
.IP "\(bu" 2
\fCstd::fstream\fP 
.IP "\(bu" 2
\fCstd::wifstream\fP 
.IP "\(bu" 2
\fCstd::wfstream\fP 
.PP
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIStreamType\fP Class derived from \fCstd::basic_istream\fP\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
