.TH "CrtAllocator" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CrtAllocator \- C-runtime library allocator\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <allocators\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void * \fBMalloc\fP (size_t size)"
.br
.ti -1c
.RI "void * \fBRealloc\fP (void *originalPtr, size_t originalSize, size_t newSize)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBFree\fP (void *ptr)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const bool \fBkNeedFree\fP = true"
.br
.in -1c
.SH "Detailed Description"
.PP 
C-runtime library allocator\&. 

This class is just wrapper for standard C library memory routines\&. 
.PP
\fBNote:\fP
.RS 4
implements Allocator concept 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
