.TH "EncodedOutputStream< Encoding, OutputByteStream >" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EncodedOutputStream< Encoding, OutputByteStream > \- Output byte stream wrapper with statically bound encoding\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <encodedstream\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Encoding::Ch \fBCh\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEncodedOutputStream\fP (OutputByteStream &os, bool putBOM=true)"
.br
.ti -1c
.RI "void \fBPut\fP (Ch c)"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.ti -1c
.RI "Ch \fBPeek\fP () const"
.br
.ti -1c
.RI "Ch \fBTake\fP ()"
.br
.ti -1c
.RI "size_t \fBTell\fP () const"
.br
.ti -1c
.RI "Ch * \fBPutBegin\fP ()"
.br
.ti -1c
.RI "size_t \fBPutEnd\fP (Ch *)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Encoding, typename OutputByteStream>
.br
class EncodedOutputStream< Encoding, OutputByteStream >"
Output byte stream wrapper with statically bound encoding\&. 


.PP
\fBTemplate Parameters:\fP
.RS 4
\fIEncoding\fP The interpretation of encoding of the stream\&. Either \fBUTF8\fP, \fBUTF16LE\fP, \fBUTF16BE\fP, \fBUTF32LE\fP, \fBUTF32BE\fP\&. 
.br
\fIOutputByteStream\fP Type of input byte stream\&. For example, \fBFileWriteStream\fP\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
