.TH "EncodedInputStream< UTF8<>, MemoryStream >" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EncodedInputStream< UTF8<>, MemoryStream > \- Specialized for \fBUTF8\fP \fBMemoryStream\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <encodedstream\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBUTF8\fP ::Ch \fBCh\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEncodedInputStream\fP (\fBMemoryStream\fP &is)"
.br
.ti -1c
.RI "Ch \fBPeek\fP () const"
.br
.ti -1c
.RI "Ch \fBTake\fP ()"
.br
.ti -1c
.RI "size_t \fBTell\fP () const"
.br
.ti -1c
.RI "void \fBPut\fP (Ch)"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.ti -1c
.RI "Ch * \fBPutBegin\fP ()"
.br
.ti -1c
.RI "size_t \fBPutEnd\fP (Ch *)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBMemoryStream\fP & \fBis_\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<>
.br
class EncodedInputStream< UTF8<>, MemoryStream >"
Specialized for \fBUTF8\fP \fBMemoryStream\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
