.TH "rapidjson/error/error.h" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rapidjson/error/error.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include '\&.\&./rapidjson\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBParseResult\fP"
.br
.RI "Result of parsing (wraps ParseErrorCode) "
.in -1c
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBRAPIDJSON_ERROR_CHARTYPE\fP   char"
.br
.RI "Character type of error messages\&. "
.ti -1c
.RI "#define \fBRAPIDJSON_ERROR_STRING\fP(x)   x"
.br
.RI "Macro for converting string literial to \fBRAPIDJSON_ERROR_CHARTYPE\fP[]\&. "
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef const \fBRAPIDJSON_ERROR_CHARTYPE\fP *(* \fBGetParseErrorFunc\fP) (\fBParseErrorCode\fP)"
.br
.RI "Function pointer type of GetParseError()\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBParseErrorCode\fP { \fBkParseErrorNone\fP = 0, \fBkParseErrorDocumentEmpty\fP, \fBkParseErrorDocumentRootNotSingular\fP, \fBkParseErrorValueInvalid\fP, \fBkParseErrorObjectMissName\fP, \fBkParseErrorObjectMissColon\fP, \fBkParseErrorObjectMissCommaOrCurlyBracket\fP, \fBkParseErrorArrayMissCommaOrSquareBracket\fP, \fBkParseErrorStringUnicodeEscapeInvalidHex\fP, \fBkParseErrorStringUnicodeSurrogateInvalid\fP, \fBkParseErrorStringEscapeInvalid\fP, \fBkParseErrorStringMissQuotationMark\fP, \fBkParseErrorStringInvalidEncoding\fP, \fBkParseErrorNumberTooBig\fP, \fBkParseErrorNumberMissFraction\fP, \fBkParseErrorNumberMissExponent\fP, \fBkParseErrorTermination\fP, \fBkParseErrorUnspecificSyntaxError\fP }
.RI "Error code of parsing\&. ""
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
