.TH "exaColData< T >" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exaColData< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBexaTblColumn\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexaColData\fP (std::vector< T > *data)"
.br
.ti -1c
.RI "\fBexaColData\fP (char *data)"
.br
.ti -1c
.RI "T \fBoperator[]\fP (size_t position)"
.br
.in -1c
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
