.TH "exaResultSet" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exaResultSet \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBexaResultSet\fP \fBgetRows\fP (int start_row_no, int stop_row_no=\-1)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
