.TH "exaTblColumn" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
exaTblColumn \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBexaColData< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBexaTblColumn\fP (char name, int datatype, int precision=0, int scale=0)"
.br
.ti -1c
.RI "virtual void \fBoperator[]\fP (size_t position)"
.br
.ti -1c
.RI "virtual void \fBappendData\fP (char *data, size_t start=1;size_t stop=0)"
.br
.ti -1c
.RI "int \fBcount\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBtype\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
