.TH "FileWriteStream" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileWriteStream \- Wrapper of C file stream for input using fread()\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <filewritestream\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef char \fBCh\fP"
.br
.RI "Character type\&. Only support char\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileWriteStream\fP (std::FILE *fp, char *buffer, size_t bufferSize)"
.br
.ti -1c
.RI "void \fBPut\fP (char c)"
.br
.ti -1c
.RI "void \fBPutN\fP (char c, size_t n)"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.ti -1c
.RI "char \fBPeek\fP () const"
.br
.ti -1c
.RI "char \fBTake\fP ()"
.br
.ti -1c
.RI "size_t \fBTell\fP () const"
.br
.ti -1c
.RI "char * \fBPutBegin\fP ()"
.br
.ti -1c
.RI "size_t \fBPutEnd\fP (char *)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Wrapper of C file stream for input using fread()\&. 


.PP
\fBNote:\fP
.RS 4
implements Stream concept 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
