.TH "FileReadStream" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
FileReadStream \- File byte stream for input using fread()\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <filereadstream\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef char \fBCh\fP"
.br
.RI "Character type (byte)\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileReadStream\fP (std::FILE *fp, char *buffer, size_t bufferSize)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "\fBCh\fP \fBPeek\fP () const"
.br
.ti -1c
.RI "\fBCh\fP \fBTake\fP ()"
.br
.ti -1c
.RI "size_t \fBTell\fP () const"
.br
.ti -1c
.RI "void \fBPut\fP (\fBCh\fP)"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.ti -1c
.RI "\fBCh\fP * \fBPutBegin\fP ()"
.br
.ti -1c
.RI "size_t \fBPutEnd\fP (\fBCh\fP *)"
.br
.ti -1c
.RI "const \fBCh\fP * \fBPeek4\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 
File byte stream for input using fread()\&. 


.PP
\fBNote:\fP
.RS 4
implements Stream concept 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "FileReadStream::FileReadStream (std::FILE * fp, char * buffer, size_t bufferSize)\fC [inline]\fP"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIfp\fP File pointer opened for read\&. 
.br
\fIbuffer\fP user-supplied buffer\&. 
.br
\fIbufferSize\fP size of buffer in bytes\&. Must >=4 bytes\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
