.TH "GenericMember< Encoding, Allocator >" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericMember< Encoding, Allocator > \- Name-value pair in a JSON object value\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <document\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBGenericValue\fP< Encoding, Allocator > \fBname\fP"
.br
.RI "name of member (must be a string) "
.ti -1c
.RI "\fBGenericValue\fP< Encoding, Allocator > \fBvalue\fP"
.br
.RI "value of member\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Encoding, typename Allocator>
.br
struct GenericMember< Encoding, Allocator >"
Name-value pair in a JSON object value\&. 

This class was internal to \fBGenericValue\fP\&. It used to be a inner struct\&. But a compiler (IBM XL C/C++ for AIX) have reported to have problem with that so it moved as a namespace scope struct\&. https://code.google.com/p/rapidjson/issues/detail?id=64 

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
