.TH "GenericStringBuffer< Encoding, Allocator >" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericStringBuffer< Encoding, Allocator > \- Represents an in-memory output stream\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stringbuffer\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef Encoding::Ch \fBCh\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenericStringBuffer\fP (Allocator *allocator=0, size_t capacity=kDefaultCapacity)"
.br
.ti -1c
.RI "void \fBPut\fP (Ch c)"
.br
.ti -1c
.RI "void \fBPutUnsafe\fP (Ch c)"
.br
.ti -1c
.RI "void \fBFlush\fP ()"
.br
.ti -1c
.RI "void \fBClear\fP ()"
.br
.ti -1c
.RI "void \fBShrinkToFit\fP ()"
.br
.ti -1c
.RI "void \fBReserve\fP (size_t count)"
.br
.ti -1c
.RI "Ch * \fBPush\fP (size_t count)"
.br
.ti -1c
.RI "Ch * \fBPushUnsafe\fP (size_t count)"
.br
.ti -1c
.RI "void \fBPop\fP (size_t count)"
.br
.ti -1c
.RI "const Ch * \fBGetString\fP () const"
.br
.ti -1c
.RI "size_t \fBGetSize\fP () const"
.br
.RI "Get the size of string in bytes in the string buffer\&. "
.ti -1c
.RI "size_t \fBGetLength\fP () const"
.br
.RI "Get the length of string in Ch in the string buffer\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBinternal::Stack\fP< Allocator > \fBstack_\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const size_t \fBkDefaultCapacity\fP = 256"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Encoding, typename Allocator = CrtAllocator>
.br
class GenericStringBuffer< Encoding, Allocator >"
Represents an in-memory output stream\&. 


.PP
\fBTemplate Parameters:\fP
.RS 4
\fIEncoding\fP Encoding of the stream\&. 
.br
\fIAllocator\fP type for allocating memory buffer\&. 
.RE
.PP
\fBNote:\fP
.RS 4
implements Stream concept 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
