.TH "GenericValue< Encoding, Allocator >::String" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericValue< Encoding, Allocator >::String \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBSizeType\fP \fBlength\fP"
.br
.ti -1c
.RI "\fBSizeType\fP \fBhashcode\fP"
.br
.RI "reserved "
.ti -1c
.RI "const \fBCh\fP * \fBstr\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
