.TH "GenericValue< Encoding, Allocator >::Flag" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericValue< Encoding, Allocator >::Flag \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "char \fBpayload\fP [sizeof(\fBSizeType\fP) *2+sizeof(void *)+2]"
.br
.ti -1c
.RI "uint16_t \fBflags\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
