.TH "GenericValue< Encoding, Allocator >::Data" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericValue< Encoding, Allocator >::Data \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBString\fP \fBs\fP"
.br
.ti -1c
.RI "\fBShortString\fP \fBss\fP"
.br
.ti -1c
.RI "\fBNumber\fP \fBn\fP"
.br
.ti -1c
.RI "\fBObjectData\fP \fBo\fP"
.br
.ti -1c
.RI "\fBArrayData\fP \fBa\fP"
.br
.ti -1c
.RI "\fBFlag\fP \fBf\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
