.TH "GenericValue< Encoding, Allocator >::Number" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericValue< Encoding, Allocator >::Number \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBI\fP"
.br
.ti -1c
.RI "struct \fBU\fP"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "struct \fBGenericValue::Number::I\fP \fBi\fP"
.br
.ti -1c
.RI "struct \fBGenericValue::Number::U\fP \fBu\fP"
.br
.ti -1c
.RI "int64_t \fBi64\fP"
.br
.ti -1c
.RI "uint64_t \fBu64\fP"
.br
.ti -1c
.RI "double \fBd\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
