.TH "GenericArray< Const, ValueT >" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericArray< Const, ValueT > \- Helper class for accessing Value of array type\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <document\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef \fBGenericArray\fP< true, ValueT > \fBConstArray\fP"
.br
.ti -1c
.RI "typedef \fBGenericArray\fP< false, ValueT > \fBArray\fP"
.br
.ti -1c
.RI "typedef ValueT \fBPlainType\fP"
.br
.ti -1c
.RI "typedef internal::MaybeAddConst< Const, PlainType >::\fBType\fP \fBValueType\fP"
.br
.ti -1c
.RI "typedef ValueType * \fBValueIterator\fP"
.br
.ti -1c
.RI "typedef const ValueT * \fBConstValueIterator\fP"
.br
.ti -1c
.RI "typedef ValueType::AllocatorType \fBAllocatorType\fP"
.br
.ti -1c
.RI "typedef ValueType::StringRefType \fBStringRefType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenericArray\fP (const \fBGenericArray\fP &rhs)"
.br
.ti -1c
.RI "\fBGenericArray\fP & \fBoperator=\fP (const \fBGenericArray\fP &rhs)"
.br
.ti -1c
.RI "\fBSizeType\fP \fBSize\fP () const"
.br
.ti -1c
.RI "\fBSizeType\fP \fBCapacity\fP () const"
.br
.ti -1c
.RI "bool \fBEmpty\fP () const"
.br
.ti -1c
.RI "void \fBClear\fP () const"
.br
.ti -1c
.RI "ValueType & \fBoperator[]\fP (\fBSizeType\fP index) const"
.br
.ti -1c
.RI "ValueIterator \fBBegin\fP () const"
.br
.ti -1c
.RI "ValueIterator \fBEnd\fP () const"
.br
.ti -1c
.RI "\fBGenericArray\fP \fBReserve\fP (\fBSizeType\fP newCapacity, AllocatorType &allocator) const"
.br
.ti -1c
.RI "\fBGenericArray\fP \fBPushBack\fP (ValueType &value, AllocatorType &allocator) const"
.br
.ti -1c
.RI "\fBGenericArray\fP \fBPushBack\fP (StringRefType value, AllocatorType &allocator) const"
.br
.ti -1c
.RI "template<typename T > \fBRAPIDJSON_DISABLEIF_RETURN\fP ((internal::OrExpr< internal::IsPointer< T >, \fBinternal::IsGenericValue\fP< T > >),(const \fBGenericArray\fP &)) PushBack(T value"
.br
.ti -1c
.RI "\fBGenericArray\fP \fBPopBack\fP () const"
.br
.ti -1c
.RI "ValueIterator \fBErase\fP (ConstValueIterator pos) const"
.br
.ti -1c
.RI "ValueIterator \fBErase\fP (ConstValueIterator first, ConstValueIterator last) const"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "AllocatorType &allocator \fBconst\fP { value_\&.PushBack(value, allocator)"
.br
.ti -1c
.RI "return * \fBthis\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "template<typename , typename > class \fBGenericValue\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<bool Const, typename ValueT>
.br
class GenericArray< Const, ValueT >"
Helper class for accessing Value of array type\&. 

Instance of this helper class is obtained by \fCGenericValue::GetArray()\fP\&. In addition to all APIs for array type, it provides range-based for loop if \fCRAPIDJSON_HAS_CXX11_RANGE_FOR=1\fP\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
