.TH "GenericValue< Encoding, Allocator >::ShortString" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericValue< Encoding, Allocator >::ShortString \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBMaxChars\fP = sizeof(static_cast<Flag*>(0)->payload) / sizeof(Ch), \fBMaxSize\fP = MaxChars - 1, \fBLenPos\fP = MaxSize }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetLength\fP (\fBSizeType\fP len)"
.br
.ti -1c
.RI "\fBSizeType\fP \fBGetLength\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBUsable\fP (\fBSizeType\fP len)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBCh\fP \fBstr\fP [MaxChars]"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
