.TH "internal::StreamLocalCopy< Stream, 1 >" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::StreamLocalCopy< Stream, 1 > \- Do copy optimization\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <reader\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStreamLocalCopy\fP (Stream &original)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "Stream \fBs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Stream>
.br
class internal::StreamLocalCopy< Stream, 1 >"
Do copy optimization\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
