.TH "internal::DecodedStream< SourceStream, Encoding >" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::DecodedStream< SourceStream, Encoding > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDecodedStream\fP (SourceStream &ss)"
.br
.ti -1c
.RI "unsigned \fBPeek\fP ()"
.br
.ti -1c
.RI "unsigned \fBTake\fP ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
