.TH "internal::TypeHelper< ValueType, typename ValueType::Array >" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::TypeHelper< ValueType, typename ValueType::Array > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef ValueType::Array \fBArrayType\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBIs\fP (const ValueType &v)"
.br
.ti -1c
.RI "static ArrayType \fBGet\fP (ValueType &v)"
.br
.ti -1c
.RI "static ValueType & \fBSet\fP (ValueType &v, ArrayType data)"
.br
.ti -1c
.RI "static ValueType & \fBSet\fP (ValueType &v, ArrayType data, typename ValueType::AllocatorType &)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
