.TH "internal::Hasher< Encoding, Allocator >::Number::U" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::Hasher< Encoding, Allocator >::Number::U \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "uint64_t \fBu\fP"
.br
.ti -1c
.RI "int64_t \fBi\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
