.TH "internal::ISchemaValidator" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::ISchemaValidator \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBGenericSchemaValidator< SchemaDocumentType, OutputHandler, StateAllocator >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual bool \fBIsValid\fP () const =0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
