.TH "internal::TypeHelper< ValueType, const typename ValueType::Ch * >" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::TypeHelper< ValueType, const typename ValueType::Ch * > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef const ValueType::Ch * \fBStringType\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBIs\fP (const ValueType &v)"
.br
.ti -1c
.RI "static StringType \fBGet\fP (const ValueType &v)"
.br
.ti -1c
.RI "static ValueType & \fBSet\fP (ValueType &v, const StringType data)"
.br
.ti -1c
.RI "static ValueType & \fBSet\fP (ValueType &v, const StringType data, typename ValueType::AllocatorType &a)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
