.TH "internal::Double" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::Double \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDouble\fP (double d)"
.br
.ti -1c
.RI "\fBDouble\fP (uint64_t u)"
.br
.ti -1c
.RI "double \fBValue\fP () const"
.br
.ti -1c
.RI "uint64_t \fBUint64Value\fP () const"
.br
.ti -1c
.RI "double \fBNextPositiveDouble\fP () const"
.br
.ti -1c
.RI "bool \fBSign\fP () const"
.br
.ti -1c
.RI "uint64_t \fBSignificand\fP () const"
.br
.ti -1c
.RI "int \fBExponent\fP () const"
.br
.ti -1c
.RI "bool \fBIsNan\fP () const"
.br
.ti -1c
.RI "bool \fBIsInf\fP () const"
.br
.ti -1c
.RI "bool \fBIsNanOrInf\fP () const"
.br
.ti -1c
.RI "bool \fBIsNormal\fP () const"
.br
.ti -1c
.RI "bool \fBIsZero\fP () const"
.br
.ti -1c
.RI "uint64_t \fBIntegerSignificand\fP () const"
.br
.ti -1c
.RI "int \fBIntegerExponent\fP () const"
.br
.ti -1c
.RI "uint64_t \fBToBias\fP () const"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static unsigned \fBEffectiveSignificandSize\fP (int order)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
