.TH "internal::ISchemaStateFactory< SchemaType >" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::ISchemaStateFactory< SchemaType > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fBISchemaValidator\fP * \fBCreateSchemaValidator\fP (const SchemaType &)=0"
.br
.ti -1c
.RI "virtual void \fBDestroySchemaValidator\fP (\fBISchemaValidator\fP *validator)=0"
.br
.ti -1c
.RI "virtual void * \fBCreateHasher\fP ()=0"
.br
.ti -1c
.RI "virtual uint64_t \fBGetHashCode\fP (void *hasher)=0"
.br
.ti -1c
.RI "virtual void \fBDestroryHasher\fP (void *hasher)=0"
.br
.ti -1c
.RI "virtual void * \fBMallocState\fP (size_t size)=0"
.br
.ti -1c
.RI "virtual void \fBFreeState\fP (void *p)=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
