.TH "internal::GenericRegexSearch< RegexType, Allocator >" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::GenericRegexSearch< RegexType, Allocator > \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef RegexType::EncodingType \fBEncoding\fP"
.br
.ti -1c
.RI "typedef Encoding::Ch \fBCh\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenericRegexSearch\fP (const RegexType &regex, Allocator *allocator=0)"
.br
.ti -1c
.RI "template<typename InputStream > bool \fBMatch\fP (InputStream &is)"
.br
.ti -1c
.RI "bool \fBMatch\fP (const Ch *s)"
.br
.ti -1c
.RI "template<typename InputStream > bool \fBSearch\fP (InputStream &is)"
.br
.ti -1c
.RI "bool \fBSearch\fP (const Ch *s)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
