.TH "internal::TypeHelper< ValueType, unsigned >" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
internal::TypeHelper< ValueType, unsigned > \- 
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBIs\fP (const ValueType &v)"
.br
.ti -1c
.RI "static unsigned \fBGet\fP (const ValueType &v)"
.br
.ti -1c
.RI "static ValueType & \fBSet\fP (ValueType &v, unsigned data)"
.br
.ti -1c
.RI "static ValueType & \fBSet\fP (ValueType &v, unsigned data, typename ValueType::AllocatorType &)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
