.TH "rapidjson" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
rapidjson \- main RapidJSON namespace  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAllocator\fP"
.br
.RI "Concept for allocating, resizing and freeing memory block\&. "
.ti -1c
.RI "class \fBEncoding\fP"
.br
.RI "Concept for encoding of Unicode characters\&. "
.ti -1c
.RI "class \fBHandler\fP"
.br
.RI "Concept for receiving events from \fBGenericReader\fP upon parsing\&. The functions return true if no error occurs\&. If they return false, the event publisher should terminate the process\&. "
.ti -1c
.RI "class \fBStream\fP"
.br
.RI "Concept for reading and writing characters\&. "
.in -1c
.SH "Detailed Description"
.PP 
main RapidJSON namespace 


.PP
\fBSee also:\fP
.RS 4
\fBRAPIDJSON_NAMESPACE\fP 
.RE
.PP

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
