.TH "SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator > \- A helper class for parsing with validation\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <schema\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "typedef SchemaDocumentType::PointerType \fBPointerType\fP"
.br
.ti -1c
.RI "typedef InputStream::Ch \fBCh\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSchemaValidatingReader\fP (InputStream &is, const SchemaDocumentType &sd)"
.br
.RI "Constructor\&. "
.ti -1c
.RI "template<typename Handler > bool \fBoperator()\fP (Handler &handler)"
.br
.ti -1c
.RI "const \fBParseResult\fP & \fBGetParseResult\fP () const"
.br
.ti -1c
.RI "bool \fBIsValid\fP () const"
.br
.ti -1c
.RI "const PointerType & \fBGetInvalidSchemaPointer\fP () const"
.br
.ti -1c
.RI "const Ch * \fBGetInvalidSchemaKeyword\fP () const"
.br
.ti -1c
.RI "const PointerType & \fBGetInvalidDocumentPointer\fP () const"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<unsigned parseFlags, typename InputStream, typename SourceEncoding, typename SchemaDocumentType = SchemaDocument, typename StackAllocator = CrtAllocator>
.br
class SchemaValidatingReader< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >"
A helper class for parsing with validation\&. 

This helper class is a functor, designed as a parameter of \fBGenericDocument::Populate()\fP\&.
.PP
\fBTemplate Parameters:\fP
.RS 4
\fIparseFlags\fP Combination of \fBParseFlag\fP\&. 
.br
\fIInputStream\fP Type of input stream, implementing Stream concept\&. 
.br
\fISourceEncoding\fP Encoding of the input stream\&. 
.br
\fISchemaDocumentType\fP Type of schema document\&. 
.br
\fIStackAllocator\fP Allocator type for stack\&. 
.RE
.PP

.SH "Constructor & Destructor Documentation"
.PP 
.SS "template<unsigned parseFlags, typename InputStream , typename SourceEncoding , typename SchemaDocumentType  = SchemaDocument, typename StackAllocator  = CrtAllocator> \fBSchemaValidatingReader\fP< parseFlags, InputStream, SourceEncoding, SchemaDocumentType, StackAllocator >::\fBSchemaValidatingReader\fP (InputStream & is, const SchemaDocumentType & sd)\fC [inline]\fP"

.PP
Constructor\&. 
.PP
\fBParameters:\fP
.RS 4
\fIis\fP Input stream\&. 
.br
\fIsd\fP Schema document\&. 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
