.TH "StreamTraits< Stream >" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StreamTraits< Stream > \- Provides additional information for stream\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <stream\&.h>\fP
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum { \fBcopyOptimization\fP = 0 }
.RI "Whether to make local copy of stream for optimization during parsing\&. ""
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Stream>
.br
struct StreamTraits< Stream >"
Provides additional information for stream\&. 

By using traits pattern, this type provides a default configuration for stream\&. For custom stream, this type can be specialized for other configuration\&. See TEST(Reader, CustomStringStream) in readertest\&.cpp for example\&. 
.SH "Member Enumeration Documentation"
.PP 
.SS "template<typename Stream > anonymous enum"

.PP
Whether to make local copy of stream for optimization during parsing\&. By default, for safety, streams do not use local copy optimization\&. Stream that can be copied fast should specialize this, like StreamTraits<StringStream>\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
