.TH "Transcoder< Encoding, Encoding >" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transcoder< Encoding, Encoding > \- Specialization of \fBTranscoder\fP with same source and target encoding\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <encodings\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename InputStream , typename OutputStream > static RAPIDJSON_FORCEINLINE bool \fBTranscode\fP (InputStream &is, OutputStream &os)"
.br
.ti -1c
.RI "template<typename InputStream , typename OutputStream > static RAPIDJSON_FORCEINLINE bool \fBTranscodeUnsafe\fP (InputStream &is, OutputStream &os)"
.br
.ti -1c
.RI "template<typename InputStream , typename OutputStream > static RAPIDJSON_FORCEINLINE bool \fBValidate\fP (InputStream &is, OutputStream &os)"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename Encoding>
.br
struct Transcoder< Encoding, Encoding >"
Specialization of \fBTranscoder\fP with same source and target encoding\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
