.TH "Transcoder< SourceEncoding, TargetEncoding >" 3 "Thu Nov 3 2016" "Version 0.9" "EXASockets" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Transcoder< SourceEncoding, TargetEncoding > \- Encoding conversion\&.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <encodings\&.h>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "template<typename InputStream , typename OutputStream > static RAPIDJSON_FORCEINLINE bool \fBTranscode\fP (InputStream &is, OutputStream &os)"
.br
.RI "Take one Unicode codepoint from source encoding, convert it to target encoding and put it to the output stream\&. "
.ti -1c
.RI "template<typename InputStream , typename OutputStream > static RAPIDJSON_FORCEINLINE bool \fBTranscodeUnsafe\fP (InputStream &is, OutputStream &os)"
.br
.ti -1c
.RI "template<typename InputStream , typename OutputStream > static RAPIDJSON_FORCEINLINE bool \fBValidate\fP (InputStream &is, OutputStream &os)"
.br
.RI "Validate one Unicode codepoint from an encoded stream\&. "
.in -1c
.SH "Detailed Description"
.PP 

.SS "template<typename SourceEncoding, typename TargetEncoding>
.br
struct Transcoder< SourceEncoding, TargetEncoding >"
Encoding conversion\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for EXASockets from the source code\&.
